### ISSUE TITLE
base.data.Heap: add insert function

### ISSUE THREAD

**Issue by loewenheim** [unisonweb/base#115]
This adds an `insert` function to `base.data.Heap`. It's implemented in terms of `singleton` and `union`.

## Code review
```
The changes summarized below are available for you to review, using the following command:
  
    pull-request.load unison.public.base.latest loewenheim.public.prs.base.heapInsert
  
  Added definitions:
  
     Heap.insert.doc : Doc (+1 metadata)
     Heap.insert     : k -> v -> Heap k v -> Heap k v (+1 metadata)
```

**Comment by runarorama** [comment]
A couple of things:

1. Could you also push your `Author`? Put it in `metadata.authors` alongside other Base authors. I want to make sure you're properly represented as a contributor.
2. Can you either link the Unison MIT license, or another compatible license? You can also just comment here if you're assigning the copyright of this to Unison Computing.
3. It makes no difference in this case, but in general PRs should be made against `main`, rather than `latest`.

**Comment by runarorama** [comment]
Oh, I have the hash of your `Author` and `GUID`, so I'll just give them names under `metadata.authors`. I think we're good to go.

**Comment by runarorama** [comment]
Merged into `main`. 🌈⭐
