### ISSUE TITLE
PR to add Function.tap and Debug.tap

### ISSUE THREAD

**Issue by pragdave** [unisonweb/base#137]
I don't seem to be able to create a proper PR atm, but I'm posting source if that's useful.

Otherwise I'll wait until main gets sorted.

Dave

~~~ unison
{{
  `tap tappedFunction param` applies `param` to `tappedFunction`, discarding the result.
  It then returns `param`.
  
  This is used to insert an activity into a pipeline without
  impacting the execution of that pipeline.
  
  # Example
  
  ```
  [ 1, 2, 3 ]
    |> map Nat.increment
    |> Function.tap (Debug.trace "incremented")
    |> sum
  ```
  
  # See also
  
  {Debug.tap}
}}

Function.tap: (a -> Unit) -> a -> a
Function.tap tappedFunction param =
  tappedFunction param
  param


test> Function.tap.tests.t1 = check let
  use Nat == +
  ( 99, 100 ) === (withInitialValue 0 do
    use Store get put
    put 0
    tapper n = put (n + 1)
    result = Function.tap tapper 99
    (result, get)
  ) 

{{
  ``Debug.tap t v`` evaluates `Debug.trace t v` and then returns
  the value v, allowing you to trace intermediate values in pipelines.

  # Example
  
  ```
  [ 1, 2, 3 ]
      |> map Nat.increment
      |> Debug.tap "incremented"
      |> sum
  ```
  
  # See also
  
  {Function.tap}
}}

Debug.tap: Text -> a -> a
Debug.tap =
  Function.tap << Debug.trace
~~~

**Comment by runarorama** [comment]
I've added this to Base, here: https://share.unison-lang.org/@unison/p/code/latest/namespaces/public/base/main/;/terms/Function/tap

Note that I changed some of the doc formatting. Currently the syntax for monospace is enclosing in pairs of double apostrophes (`''like this''`).

I also changed the examples to `@typecheck` instead of evaluate, as Doc evaluation is not allowed to call `trace`.

Added example output.

I also created `metadata.authors.pragdave` and linked it to these definitions. Please use this author object as your default going forward when contributing to Base.

Thank you! 🌈⭐
