### ISSUE TITLE
Swap parameters to Natural.parse?

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base#66]
Currently `Natural.parse` has the signature `Text -> Nat -> Optional Natural` where the `Text` is something like `d8a2` and the `Nat` is a radix (like 16).

But it seems like it would be much more common to fix a radix and then parse multiple strings than it would be to fix a string and then try to parse it in several different ...radices? Should the argument order be swapped?

If it is, then `parse!`, `toText` and `toText!` should also be changed.

**Comment by aryairani** [comment]
It would be a not-automatically-propagatable change until we have the ability to represent parameter reordering in a patch.

**Comment by anovstrup** [comment]
@aryairani No, but there's nothing fundamentally wrong with the existing definitions.  The proposed change could just introduce new definitions (repurposing the names) so that existing code can continue using the current definitions, and the current definitions could be renamed (e.g., `Natural.parse` -> `Natural.parse.deprecated`) to avoid existing references to them showing up as hashes.

**Comment by aryairani** [comment]
@anovstrup Totally.
